### ISSUE TITLE
shift button as shortcut key doesn’t work

### ISSUE THREAD

**Issue by anhduong89** [wmchris/DellXPS15-9550-OSX#127]
hi folks,
surfing with OSX in dell XPS is completely satisfied. However, my caps lock only enables highcase. I can’t process any shortcut keys that including caps lock. 
Any solution for that?

**Comment by ghost** [comment]
I have noticed that no one want to help you. The reason why is because you are not reading the tutorial. As for the CAPS lock as hot key. Youll have to remap that. Just find some info on the web. Trust me. You'll find your answer if you put an effort

**Comment by anhduong89** [comment]
> I have noticed that no one want to help you. The reason why is because you are not reading the tutorial. As for the CAPS lock as hot key. Youll have to remap that. Just find some info on the web. Trust me. You'll find your answer if you put an effort

thank for comment. I apparently did search for the solution on google and another resources. just that it took too much time for me to solve as I'm new to hackintosh.

Also, I tried keyboard checked and see my capslock was mapped. I can't find any tutorial for  "hotkey mapping" , only mapping from button to another button

**Comment by anhduong89** [comment]
for example, in my PC, if I press:

command + R : refresh page

capslock + command + R :  refresh page ( it actually has to open reader mode of page )

capslock : CAPS key

capslock was disable as shortcut key. Does it mean I have to remap all shortcut key with my current capslock?

**Comment by golimpio** [comment]
I'm not quite sure what the issue with the Capslock is, so forgive me if I got it wrong.

On my setup I use Capslock as a hotkey for Alfred app, so first I remapped it to F18 key and setup the hotkey in Alfred to use F18.

This is what I do to remap capslock to F18:
`
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x70000006D}]}'`

**Comment by anhduong89** [comment]
sorry guys , I was thought "upward big arrow icon" is Capslock key. It must be shift key.

but even when I press : Shift + command + R, it still doesn't work

**Comment by golimpio** [comment]
I'm running macOS 10.15.1 and I didn't find any issue with the Shift key. On Chrome, for example, I have it set to "switch to read view" and it works fine.

Could you please give an example of what you are trying to achieve?

**Comment by anhduong89** [comment]
> I'm running macOS 10.15.1 and I didn't find any issue with the Shift key. On Chrome, for example, I have it set to "switch to read view" and it works fine.
> 
> Could you please give an example of what you are trying to achieve?

hi golimpio, thank you for comment. I did want to use shift key as default shortcut key of macOS fore example, in safari, I press : shift + command + P for private window, I tried on my laptop keyboard and it worked, but it didn't work on my external mechanical keyboard.
Some said there will be unexpected error with external keyboard.

**Comment by ghost** [comment]
Not to be that guy. But this is not issue related to this tutorial. Everyone subscribed to this repo gets this notification.

**Comment by anhduong89** [comment]
> Not to be that guy. But this is not issue related to this tutorial. Everyone subscribed to this repo gets this notification.

I had used this tutorial. It should be the problem caused by it then?

you can unsubcribe the thread. Everything is on your own

**Comment by golimpio** [comment]
> > I'm running macOS 10.15.1 and I didn't find any issue with the Shift key. On Chrome, for example, I have it set to "switch to read view" and it works fine.
> > Could you please give an example of what you are trying to achieve?
> 
> hi golimpio, thank you for comment. I did want to use shift key as default shortcut key of macOS fore example, in safari, I press : shift + command + P for private window, I tried on my laptop keyboard and it worked, but it didn't work on my external mechanical keyboard.
> Some said there will be unexpected error with external keyboard.

I got it now. I don't have a mechanical keyboard, I do use an external wireless USB keyboard (Microsoft) though, and I don't have this issue with it.

I can use Cmd+Shift+N to open a new private window in Safari without any issue, I also can set a new shortcut Cmd+Shift+P for open a new private window, for example, and it works well typing from my external keyboard.

I guess your case is very specific, and I guess more people would have complained already if the Shift key wasn't working.

That said, I can only test on macOS 10.15.1, since it's the only one I have. It might be some issue with your external keyboard, or it might be related to the OS version you're running.

**Comment by ghost** [comment]
Because is not related to the tutorial. It seems like you are not understanding how to set up keybindings on your keyboard. Is not a general issue, but a specific one to your install. Probably you did not configured your keyboard correctly. 
That is why @wmchris  keeps closing your 'issues' without giving you any help.
I am susbribed to this repo to get updates and important information about this tutorial. No lack of configuration on the user's end.

**Comment by krim404** [comment]
Close it now.
To be honest, someone who can’t distinguish the capslock key from the shift key should not use experimental files from the internet to install a non supported os to a officially incompatible pc in the first place.

Also this issue has nothing to do with the supplied files from this repository. It is either a wrong keymap, a broken keyboard or just wrong usage. Also from your Name I guess you’re from China: there are so many Chinese low quality keyboards out there which can only react to a maximum of two simultaneous pressed buttons... 

I can assure you the shift key is working with multiple external keyboards as well as the original internal one. I use it every day for coding, which would be extremely hard without this functionality. 

just because you used this repository to install is no reason to use the issuing system for a quick help because you don’t want to take your time to fix it by yourself. Quote:
> (...) it took too much time for me to solve as I'm new to hackintosh.
> I had used this tutorial. It should be the problem caused by it then?

With this attitude you should call the Apple support to help you, because you used their files, too.

Btw @hackedWifi I didn’t close any ticket from this particular user if I recall correctly. There are multiple chinese users with very similar names who demand help without even the slightest clue of ... well ... anything computer related. I closed/deleted their Tickets, as most of the questions were answered in the tutorial or on google page 1.
