### ISSUE TITLE
Windows EFI wont boot

### ISSUE THREAD

**Issue by tev66** [wmchris/DellXPS15-9550-OSX#129]
I am able to see my windows efi in clover. When I select and try to boot into windows, I get a blue screen error saying device is not available (error 0xc0000001). I am able to use older clovers and boot fine into my windows, but then i am unable to boot my Catalina macos. I am also able to manually boot windows via my bios. So I'm pretty sure it is something on clover's end... would anyone know what I need to change/do?

**Comment by golimpio** [comment]
Since this seems to be related to clover itself, have you tried to ask it in the forum? People might be able to help over there, or at least someone else may have the same issue:

- https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation

I don't have Windows installed in my laptop, so I can't test or confirm this issue.

**Comment by krim404** [comment]
has nothing to do with this repository.
