### ISSUE TITLE
Black screen on HDMI display out.

### ISSUE THREAD

**Issue by azeezsker** [wmchris/DellXPS15-9550-OSX#155]
Hi,

Its long time I am struggling to fix the HDMI external display, which is black as soon as HDMI cable is connected to laptop.

My System Details (using Opecnore EFI from last published repo):

Intel Core I7 6820HQ
Platform ID: 0x191E0000

Any help will be appreciated.

Thanks

**Comment by golimpio** [comment]
I won't be of much help since I no longer have an external monitor for testing this.

I'm assuming you have a Dell XPS15 9550 and the OC settings from this repository. Have you tried different platform IDs?
E.g.: **0x19260004** **0x1916000** **0x191b0000**

The default we use for the XPS 15 is **0x191b0000**

But I used to have it set to **0x19260004** to support native HiDPI on a 4k monitor.

Just a note on **0x19260004**: it is for HD 540 gpu, but it'll work with possible side effects, in my case, sleep wasn't work properly. Based on the CPU info you gave, I assume it's a Skylake with HD 530 GPU.

**Comment by azeezsker** [comment]
I tried above IDs however they brick the graphics acceleration except 1912000.

I bought one cheap USB C to DP cable (rated for 4k @ 60 Hz) and it does the job.

However HDMI remains non working, tried various frame buffer patching tricks to no avail.

Thanks for your advise though.

**Comment by MartB** [comment]
Hijacking this thread a little bit on Monterey the HDMI port somehow "reacts" (screen starts blinking) to being plugged / unplugged but the screen never shows up on the MAC.

~~I read https://github.com/krim404/DellXPS15-9550-OSX/blob/12.0/Tutorial_12.0_Step7.md and the first thing seems to apply here, but how can i make this patch on Monterey?~~

Edit: For anyone curious, this is now handled by opencore using the `agdpmod=vit9696` line https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html

**Comment by MartB** [comment]
I solved this with https://github.com/krim404/DellXPS15-9550-OSX/pull/174 on my XPS 15 9550 1080P
