### ISSUE TITLE
Suggest support PowerNap

### ISSUE THREAD

**Issue by ii404msn** [wmchris/DellXPS15-9550-OSX#5]
If add darkhandz's last update something, could make PowerNap work?

**Comment by wmchris** [comment]
darkhandz last update? dont see an update.

**Comment by wmchris** [comment]
just wanted to update some more informations regarding this issue:
i'm currently working on fixing the hibernation, which also includes darkwake (powernap). 
While hibernation didnt work right now, darkwake is possible but may kill your filesystem because of the corruption bug.

It's not perfectly clear what's the reason of this bug, but many people think it's the HackrNVMe driver. Some drives can be patched to work with the native nvme driver from apple. However i dont want to publish a tutorial right now unless i'm sure this fixes the corruption.

More informations:
http://www.insanelymac.com/forum/topic/312803-patch-for-using-nvme-under-macos-sierra-is-ready/page-50#entry2377304

**Comment by wmchris** [comment]
the 4k fix works pretty well, using powernap for two weeks now without any corruption. i also added deep idle ssdt patch to the repository. fixed.

**Comment by Piping** [comment]
@wmchris Hi, I use the 4K fix, now I can generate the sleepimage and it wont corrupt my disk. 
However, I would not be able to wakeup and hibernationmode = 25 just reboot my computer after sleep, even though the memory dump is there.

Do you have any suggestion?

**Comment by wmchris** [comment]
hibernation is not powernap. This has nothing to do with this ticket.
