### ISSUE TITLE
10.12.4 safe to upgrade?

### ISSUE THREAD

**Issue by shawnhwei** [wmchris/DellXPS15-9550-OSX#6]
Anyone tried?

**Comment by wmchris** [comment]
it is, somehow. intelbacklight is semi incompatible right now. See https://github.com/RehabMan/OS-X-Intel-Backlight/issues/4

we need an update for this, otherwise you'll either loose the posibility to change the brightness with the keyboard commands, or you loose the lower 30% of your brightness configuration. We hope rehabman publishes a patch, soon.

**Comment by scottsanett** [comment]
Depends on the different clover configurations, the result may vary. 
For me personally I used this tutorial b[https://github.com/darkhandz/XPS15-9550-Sierra](url) by darkhandz and everything pretty much works except intelbacklight.

**Comment by wmchris** [comment]
thats pretty much the same as i said.

**Comment by scottsanett** [comment]
have already restored to 10.12.3 by time machine.

**Comment by wmchris** [comment]
fixed with https://github.com/wmchris/DellXPS15-9550-OSX/commit/e5551c25be7069367278156b9ad8690382cd4e10

**Comment by Piping** [comment]
使用 [Brightness](http://bergdesign.com/brightness/#download) 这个软件就可以调节亮度,IntelBacklight 没坏, 但是键盘按键和功能失联了
