### ISSUE TITLE
The _PTS patch causes severe battery drain while sleeping

### ISSUE THREAD

**Issue by michyprima** [wmchris/DellXPS15-9550-OSX#78]
We are talking about 10%/hr. I just disabled it and battery usage went back to normal. Any good reason to re-enable dGPU in _PTS like your SSDT is doing? My unit is working fine keeping dGPU off.

**Comment by krim404** [comment]
what files are you refering to?
ptswak is a common shutdown fix, enabling the GPU to prevent a bug which hangs the computer.

**Comment by michyprima** [comment]
Yes I'm referring to PTSWAK. You are right, this patch is needed for a correct shutdown but the _PTS function gets also called on sleep. Because of that the patch turns on DGPU also on sleep causing a severe battery drain. I can also feel the bottom of the laptop getting warm

**Comment by michyprima** [comment]
This should do the trick. I'll test in the following days if this has any adverse effects. thank you.
[SSDT-PTSWAK.aml.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/2066268/SSDT-PTSWAK.aml.zip)

**Comment by krim404** [comment]
if your tests are successful, please give me a feedback, so i can add the file to the repository

**Comment by HeavenVolkoff** [comment]
I can confirm that this drastically improves battery life during sleep. However, it can be more easily archived by changing `Name(DPTS, 1)` to `Name(DPTS, 0)` in `ACPI/patched/SSDT-Config` instead of changing the `SSDT-PTSWAK` patch directly, as the patch already uses this variable to control if this specific behaviour is enabled or not, and on `SSDT-Disable_DGPU` we already disable the discrete GPU on boot so there is no need to do it again before sleep as far as I know.

**Comment by michyprima** [comment]
During my tests I didn't experience any side effects. Battery life is near perfect now.

**Comment by krim404** [comment]
@HeavenVolkoff if you disable it in config, you can experience issues on wake from sleep (at least in the past).  His patch just removes the poweron itself, so technically it should also be problematic.

But: didnt have any issue either. so push to live.

**Comment by gujiangjiang** [comment]
@rehabman

The PTS patch can be improved.

**Comment by RehabMan** [comment]
> The PTS patch can be improved.

No idea what you're referring to.
